# ----------------------------------------------------------------------
# | Strict Transport Security                                         |
# ----------------------------------------------------------------------
# Force HTTPS for all subdomains. Only meaningful if the client
# connects directly to nginx (not behind Cloudflare).
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
