apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maxterview-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/notseekeru/gitops.git
    path: apps/maxterview/overlays/staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: maxterview-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
