apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: ghcr.io/notseekeru/diagram_backend
  newName: ghcr.io/notseekeru/diagram_backend
  newTag: bde106a4e24372b1b65487cccbed73e4a3468984
- name: ghcr.io/notseekeru/diagram_frontend
  newName: ghcr.io/notseekeru/diagram_frontend
  newTag: bde106a4e24372b1b65487cccbed73e4a3468984
