apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: ghcr.io/notseekeru/diagram_backend
  newName: ghcr.io/notseekeru/diagram_backend
  newTag: f90e615d97aa8366e1d6860a9830cc1ddaaea5c6
- name: ghcr.io/notseekeru/diagram_frontend
  newName: ghcr.io/notseekeru/diagram_frontend
  newTag: f90e615d97aa8366e1d6860a9830cc1ddaaea5c6
