apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: ghcr.io/notseekeru/diagram_backend
  newName: ghcr.io/notseekeru/diagram_backend
  newTag: b3ef75f22dcd912593711d03a1e5f045e30d0364
- name: ghcr.io/notseekeru/diagram_frontend
  newName: ghcr.io/notseekeru/diagram_frontend
  newTag: b3ef75f22dcd912593711d03a1e5f045e30d0364
