apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
      - mime.types
      - conf.d/default.conf
      - conf.d/portfolio.conf
      - h5bp/basic.conf
      - h5bp/cross-origin/requests.conf
      - h5bp/location/security_file_access.conf
      - h5bp/security/content-security-policy.conf
      - h5bp/security/cross-origin-policy.conf
      - h5bp/security/permissions-policy.conf
      - h5bp/security/referrer-policy.conf
      - h5bp/security/strict-transport-security.conf
      - snippets/cloudflare-ip-ranges.conf
      - snippets/proxy-headers.conf
      - snippets/rate-limit.conf
      - snippets/resolver.conf
    options:
      disableNameSuffixHash: true
