apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- migration-job.yaml
- maxterview-ingress.yaml
images:
- name: ghcr.io/notseekeru/maxterview_backend
  newName: ghcr.io/notseekeru/maxterview_backend
  newTag: f96bfa728ce27034e45b954585fd627ec843923f
- name: ghcr.io/notseekeru/maxterview_frontend
  newName: ghcr.io/notseekeru/maxterview_frontend
  newTag: f96bfa728ce27034e45b954585fd627ec843923f
