apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Kill switch: comment an entry out to prune it (see README).
resources:
- backend.yaml
- frontend.yaml
- migration-job.yaml
- maxterview-ingress.yaml
images:
- name: ghcr.io/notseekeru/maxterview_backend
  newName: ghcr.io/notseekeru/maxterview_backend
  newTag: 048d00bd1254957e50e5e63a65914d7f8599c60b
- name: ghcr.io/notseekeru/maxterview_frontend
  newName: ghcr.io/notseekeru/maxterview_frontend
  newTag: 048d00bd1254957e50e5e63a65914d7f8599c60b
