apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- migration-job.yaml
- maxterview-ingress.yaml
images:
- name: ghcr.io/notseekeru/maxterview_backend
  newName: ghcr.io/notseekeru/maxterview_backend
  newTag: 184d4a77f32727cc0634e89e4eaedec3dd34f882
- name: ghcr.io/notseekeru/maxterview_frontend
  newName: ghcr.io/notseekeru/maxterview_frontend
  newTag: 184d4a77f32727cc0634e89e4eaedec3dd34f882
