apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: ghcr.io/notseekeru/portfolio-backend
  newName: ghcr.io/notseekeru/portfolio-backend
  newTag: 4de79a63ef21e7fc5deebce3768954db24f1a287
- name: ghcr.io/notseekeru/portfolio-frontend
  newName: ghcr.io/notseekeru/portfolio-frontend
  newTag: 4de79a63ef21e7fc5deebce3768954db24f1a287
