apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend.yaml
images:
- name: ghcr.io/notseekeru/portfolio-frontend
  newName: ghcr.io/notseekeru/portfolio-frontend
  newTag: e73d9f81dc6b2e189043ce84c615e4828333ba67
