apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
images:
- name: ghcr.io/notseekeru/portfolio-backend
  newName: ghcr.io/notseekeru/portfolio-backend
  newTag: 940382d1e434c413d31165bae0a3eb0846a785de
- name: ghcr.io/notseekeru/portfolio-frontend
  newName: ghcr.io/notseekeru/portfolio-frontend
  newTag: 940382d1e434c413d31165bae0a3eb0846a785de
